#!/bin/sh

mkdir -p /etc/nginx/sites
if [[ -e /opt/ssl/key ]] ; then
    cp /etc/nginx/sites-available/redirect.conf /etc/nginx/sites/redirect.conf
    cp /etc/nginx/sites-available/https.conf /etc/nginx/sites/https.conf
else
    cp /etc/nginx/sites-available/http.conf /etc/nginx/sites/http.conf
fi

sed -i "s/HTTP_PORT/$HTTP_PORT/g;s/HTTPS_PORT/$HTTPS_PORT/g" /etc/nginx/sites-enabled/*

exec /usr/bin/nginx 2>&1

